### ISSUE TITLE
[Feature Request] Admin-Option to allow registrations without invitation

### ISSUE THREAD

**Issue by RiekertKBW** [docmost/docmost#305] opened 2024-09-12 13:44 UTC
Hello,

I would like to have an admin-option to allow Users to register without invitations.
This would allow people who don't want to use any of the E-Mail process to allow registration without invitation.

If you have the docmost running only accessible on LAN, this could be a valid option.

**Comment by Philipinho** [comment] 2024-09-12 23:54
Duplicate of https://github.com/docmost/docmost/issues/63.

**Closed by Philipinho** 2024-09-12 23:54 UTC

**Comment by RiekertKBW** [comment] 2024-09-13 11:27
Well not exactly. 
I've seen the #63 and thought of that. 

But the feature what I'm asking for is, that you can register without being invited. On the regular "sign up" page that already exists.
This is especially interesting for larger teams/companies. 

I guess it's not that difficult to set a flag, that the registration-page is accessible for everyone, is it?

Additional what could be interesting is, that you configure a whitelist, that everyone with a specific suffix of a email-adress can register.

I've seen that in Bitwarden/Vaultwarden already. 
Here a screenshot of the Admin-Page:

![image](https://github.com/user-attachments/assets/9fb12034-2af8-4cc8-9f04-032567a4ddf0)

**Comment by Philipinho** [comment] 2024-09-13 14:16
I would say they are related. I made known my implementation strategy here https://github.com/docmost/docmost/issues/63#issuecomment-2211717507, which is similar to what you are proposing.
Feel free to add your feedback on the issue. I will weigh the feedback received when I decide to work on it.
