### ISSUE TITLE
[Feature Request] Saml / OIDC

### ISSUE THREAD

**Issue by ImChiip** [docmost/docmost#391] opened 2024-10-11 15:00 UTC
Be able to use an external SAML / OIDC authentication system (Authentik, Azure, Keycloak)

**Comment by Philipinho** [comment] 2024-10-11 16:37
Duplicate of #22. Also, see my response here: https://github.com/docmost/docmost/issues/22#issuecomment-2211018048.

**Closed by Philipinho** 2024-10-11 16:37 UTC
