### ISSUE TITLE
Tab key not behaving as expected

### ISSUE THREAD

**Issue by Dimtar** [docmost/docmost#300] opened 2024-09-11 10:54 UTC
I've noticed when editing a page in Docmost if I hit the tab key it doesn't add a tabbed space but tabs to the next page element?
Its especially noticable if there is a code block on the page as it goes to the top one on the page.

This may be the correct behavior but it doesn't seem to line up with other tools I have used.

**Comment by Zev-se** [comment] 2024-09-25 08:01
This seems to be a copy of #297

**Comment by Philipinho** [comment] 2024-10-14 08:37
Duplicate of #297.

**Closed by Philipinho** 2024-10-14 08:37 UTC

**Comment by Philipinho** [comment] 2024-11-30 14:41
This now fixed in code blocks https://github.com/docmost/docmost/pull/523.
